### ISSUE TITLE
So basically you're getting live trending info from browser via automation. Clarify me If my understanding is wrong. 

### ISSUE THREAD

**Issue by sanjaypradeep** [mytechnotalent/live_twitter_trends#1]
So basically you're getting live trending info from the browser via automation. Clarify me If my understanding is wrong.

**Comment by mytechnotalent** [comment]
Yes you are correct.

**Comment by sanjaypradeep** [comment]
Thanks for responding @mytechnotalent 

I'm in a search of Classification based ML.
